// Copyright 2025, compose-miuix-ui contributors
// SPDX-License-Identifier: Apache-2.0

package utils

import androidx.compose.ui.graphics.vector.ImageVector
import com.suqi8.coui.kmp.icon.COUIIcons
import com.suqi8.coui.kmp.icon.extended.Add
import com.suqi8.coui.kmp.icon.extended.AddCircle
import com.suqi8.coui.kmp.icon.extended.AddFolder
import com.suqi8.coui.kmp.icon.extended.Alarm
import com.suqi8.coui.kmp.icon.extended.Album
import com.suqi8.coui.kmp.icon.extended.All
import com.suqi8.coui.kmp.icon.extended.Answer
import com.suqi8.coui.kmp.icon.extended.AppRecording
import com.suqi8.coui.kmp.icon.extended.Back
import com.suqi8.coui.kmp.icon.extended.Background
import com.suqi8.coui.kmp.icon.extended.Backup
import com.suqi8.coui.kmp.icon.extended.BankCards
import com.suqi8.coui.kmp.icon.extended.Blocklist
import com.suqi8.coui.kmp.icon.extended.CallRecording
import com.suqi8.coui.kmp.icon.extended.Carrier
import com.suqi8.coui.kmp.icon.extended.ChevronBackward
import com.suqi8.coui.kmp.icon.extended.ChevronForward
import com.suqi8.coui.kmp.icon.extended.Clear
import com.suqi8.coui.kmp.icon.extended.Close
import com.suqi8.coui.kmp.icon.extended.Close2
import com.suqi8.coui.kmp.icon.extended.CloudFill
import com.suqi8.coui.kmp.icon.extended.Community
import com.suqi8.coui.kmp.icon.extended.Contacts
import com.suqi8.coui.kmp.icon.extended.ContactsBook
import com.suqi8.coui.kmp.icon.extended.ContactsCircle
import com.suqi8.coui.kmp.icon.extended.ConvertFile
import com.suqi8.coui.kmp.icon.extended.Copy
import com.suqi8.coui.kmp.icon.extended.Create
import com.suqi8.coui.kmp.icon.extended.Cut
import com.suqi8.coui.kmp.icon.extended.Delete
import com.suqi8.coui.kmp.icon.extended.Download
import com.suqi8.coui.kmp.icon.extended.Edit
import com.suqi8.coui.kmp.icon.extended.Email
import com.suqi8.coui.kmp.icon.extended.ExpandLess
import com.suqi8.coui.kmp.icon.extended.ExpandMore
import com.suqi8.coui.kmp.icon.extended.Favorites
import com.suqi8.coui.kmp.icon.extended.FavoritesFill
import com.suqi8.coui.kmp.icon.extended.File
import com.suqi8.coui.kmp.icon.extended.FileDownloads
import com.suqi8.coui.kmp.icon.extended.Filter
import com.suqi8.coui.kmp.icon.extended.Folder
import com.suqi8.coui.kmp.icon.extended.FolderFill
import com.suqi8.coui.kmp.icon.extended.Forward
import com.suqi8.coui.kmp.icon.extended.GridView
import com.suqi8.coui.kmp.icon.extended.Help
import com.suqi8.coui.kmp.icon.extended.Hide
import com.suqi8.coui.kmp.icon.extended.HorizontalSplit
import com.suqi8.coui.kmp.icon.extended.Image
import com.suqi8.coui.kmp.icon.extended.Import
import com.suqi8.coui.kmp.icon.extended.Info
import com.suqi8.coui.kmp.icon.extended.Layers
import com.suqi8.coui.kmp.icon.extended.Link
import com.suqi8.coui.kmp.icon.extended.ListView
import com.suqi8.coui.kmp.icon.extended.Location
import com.suqi8.coui.kmp.icon.extended.Lock
import com.suqi8.coui.kmp.icon.extended.MapAlbum
import com.suqi8.coui.kmp.icon.extended.Merge
import com.suqi8.coui.kmp.icon.extended.Messages
import com.suqi8.coui.kmp.icon.extended.Mic
import com.suqi8.coui.kmp.icon.extended.MicSlash
import com.suqi8.coui.kmp.icon.extended.MindMap
import com.suqi8.coui.kmp.icon.extended.Months
import com.suqi8.coui.kmp.icon.extended.More
import com.suqi8.coui.kmp.icon.extended.MoreCircle
import com.suqi8.coui.kmp.icon.extended.MoveFile
import com.suqi8.coui.kmp.icon.extended.Music
import com.suqi8.coui.kmp.icon.extended.Notes
import com.suqi8.coui.kmp.icon.extended.NotesFill
import com.suqi8.coui.kmp.icon.extended.Ok
import com.suqi8.coui.kmp.icon.extended.Paste
import com.suqi8.coui.kmp.icon.extended.Pause
import com.suqi8.coui.kmp.icon.extended.Phone
import com.suqi8.coui.kmp.icon.extended.Photos
import com.suqi8.coui.kmp.icon.extended.Pin
import com.suqi8.coui.kmp.icon.extended.Play
import com.suqi8.coui.kmp.icon.extended.Playlist
import com.suqi8.coui.kmp.icon.extended.Promotions
import com.suqi8.coui.kmp.icon.extended.Recent
import com.suqi8.coui.kmp.icon.extended.Recording
import com.suqi8.coui.kmp.icon.extended.RecordingTape
import com.suqi8.coui.kmp.icon.extended.Redo
import com.suqi8.coui.kmp.icon.extended.Refresh
import com.suqi8.coui.kmp.icon.extended.Remove
import com.suqi8.coui.kmp.icon.extended.RemoveContact
import com.suqi8.coui.kmp.icon.extended.Rename
import com.suqi8.coui.kmp.icon.extended.Replace
import com.suqi8.coui.kmp.icon.extended.Reply
import com.suqi8.coui.kmp.icon.extended.ReplyAll
import com.suqi8.coui.kmp.icon.extended.Report
import com.suqi8.coui.kmp.icon.extended.Reset
import com.suqi8.coui.kmp.icon.extended.RotateLeft
import com.suqi8.coui.kmp.icon.extended.Scan
import com.suqi8.coui.kmp.icon.extended.ScreenCapture
import com.suqi8.coui.kmp.icon.extended.ScreenMirroring
import com.suqi8.coui.kmp.icon.extended.Search
import com.suqi8.coui.kmp.icon.extended.SearchDevice
import com.suqi8.coui.kmp.icon.extended.SelectAll
import com.suqi8.coui.kmp.icon.extended.Send
import com.suqi8.coui.kmp.icon.extended.Settings
import com.suqi8.coui.kmp.icon.extended.Share
import com.suqi8.coui.kmp.icon.extended.Show
import com.suqi8.coui.kmp.icon.extended.Sidebar
import com.suqi8.coui.kmp.icon.extended.Sort
import com.suqi8.coui.kmp.icon.extended.Stopwatch
import com.suqi8.coui.kmp.icon.extended.Store
import com.suqi8.coui.kmp.icon.extended.Tasks
import com.suqi8.coui.kmp.icon.extended.Th1
import com.suqi8.coui.kmp.icon.extended.Th10
import com.suqi8.coui.kmp.icon.extended.Th11
import com.suqi8.coui.kmp.icon.extended.Th12
import com.suqi8.coui.kmp.icon.extended.Th13
import com.suqi8.coui.kmp.icon.extended.Th14
import com.suqi8.coui.kmp.icon.extended.Th15
import com.suqi8.coui.kmp.icon.extended.Th16
import com.suqi8.coui.kmp.icon.extended.Th17
import com.suqi8.coui.kmp.icon.extended.Th18
import com.suqi8.coui.kmp.icon.extended.Th19
import com.suqi8.coui.kmp.icon.extended.Th2
import com.suqi8.coui.kmp.icon.extended.Th20
import com.suqi8.coui.kmp.icon.extended.Th21
import com.suqi8.coui.kmp.icon.extended.Th22
import com.suqi8.coui.kmp.icon.extended.Th23
import com.suqi8.coui.kmp.icon.extended.Th24
import com.suqi8.coui.kmp.icon.extended.Th25
import com.suqi8.coui.kmp.icon.extended.Th26
import com.suqi8.coui.kmp.icon.extended.Th27
import com.suqi8.coui.kmp.icon.extended.Th28
import com.suqi8.coui.kmp.icon.extended.Th29
import com.suqi8.coui.kmp.icon.extended.Th3
import com.suqi8.coui.kmp.icon.extended.Th30
import com.suqi8.coui.kmp.icon.extended.Th31
import com.suqi8.coui.kmp.icon.extended.Th4
import com.suqi8.coui.kmp.icon.extended.Th5
import com.suqi8.coui.kmp.icon.extended.Th6
import com.suqi8.coui.kmp.icon.extended.Th7
import com.suqi8.coui.kmp.icon.extended.Th8
import com.suqi8.coui.kmp.icon.extended.Th9
import com.suqi8.coui.kmp.icon.extended.Theme
import com.suqi8.coui.kmp.icon.extended.Timer
import com.suqi8.coui.kmp.icon.extended.TopDownloads
import com.suqi8.coui.kmp.icon.extended.Translate
import com.suqi8.coui.kmp.icon.extended.Trim
import com.suqi8.coui.kmp.icon.extended.Tune
import com.suqi8.coui.kmp.icon.extended.Undo
import com.suqi8.coui.kmp.icon.extended.Unlock
import com.suqi8.coui.kmp.icon.extended.Unpin
import com.suqi8.coui.kmp.icon.extended.Update
import com.suqi8.coui.kmp.icon.extended.UploadCloud
import com.suqi8.coui.kmp.icon.extended.VerticalSplit
import com.suqi8.coui.kmp.icon.extended.VolumeOff
import com.suqi8.coui.kmp.icon.extended.VolumeUp
import com.suqi8.coui.kmp.icon.extended.Weeks
import com.suqi8.coui.kmp.icon.extended.WorldClock
import com.suqi8.coui.kmp.icon.extended.Years
import com.suqi8.coui.kmp.icon.extended.ZoomOut

val COUIIcons.All: Map<String, List<ImageVector>>
    get() = mapOf(
        "Light" to listOf(
            COUIIcons.Light.Add,
            COUIIcons.Light.AddCircle,
            COUIIcons.Light.AddFolder,
            COUIIcons.Light.Alarm,
            COUIIcons.Light.Album,
            COUIIcons.Light.All,
            COUIIcons.Light.Answer,
            COUIIcons.Light.AppRecording,
            COUIIcons.Light.Back,
            COUIIcons.Light.Background,
            COUIIcons.Light.Backup,
            COUIIcons.Light.BankCards,
            COUIIcons.Light.Blocklist,
            COUIIcons.Light.CallRecording,
            COUIIcons.Light.Carrier,
            COUIIcons.Light.ChevronBackward,
            COUIIcons.Light.ChevronForward,
            COUIIcons.Light.Clear,
            COUIIcons.Light.Close,
            COUIIcons.Light.Close2,
            COUIIcons.Light.CloudFill,
            COUIIcons.Light.Community,
            COUIIcons.Light.Contacts,
            COUIIcons.Light.ContactsBook,
            COUIIcons.Light.ContactsCircle,
            COUIIcons.Light.ConvertFile,
            COUIIcons.Light.Copy,
            COUIIcons.Light.Create,
            COUIIcons.Light.Cut,
            COUIIcons.Light.Delete,
            COUIIcons.Light.Download,
            COUIIcons.Light.Edit,
            COUIIcons.Light.Email,
            COUIIcons.Light.ExpandLess,
            COUIIcons.Light.ExpandMore,
            COUIIcons.Light.Favorites,
            COUIIcons.Light.FavoritesFill,
            COUIIcons.Light.File,
            COUIIcons.Light.FileDownloads,
            COUIIcons.Light.Filter,
            COUIIcons.Light.Folder,
            COUIIcons.Light.FolderFill,
            COUIIcons.Light.Forward,
            COUIIcons.Light.GridView,
            COUIIcons.Light.Help,
            COUIIcons.Light.Hide,
            COUIIcons.Light.HorizontalSplit,
            COUIIcons.Light.Image,
            COUIIcons.Light.Import,
            COUIIcons.Light.Info,
            COUIIcons.Light.Layers,
            COUIIcons.Light.Link,
            COUIIcons.Light.ListView,
            COUIIcons.Light.Location,
            COUIIcons.Light.Lock,
            COUIIcons.Light.MapAlbum,
            COUIIcons.Light.Merge,
            COUIIcons.Light.Messages,
            COUIIcons.Light.Mic,
            COUIIcons.Light.MicSlash,
            COUIIcons.Light.MindMap,
            COUIIcons.Light.Months,
            COUIIcons.Light.More,
            COUIIcons.Light.MoreCircle,
            COUIIcons.Light.MoveFile,
            COUIIcons.Light.Music,
            COUIIcons.Light.Notes,
            COUIIcons.Light.NotesFill,
            COUIIcons.Light.Ok,
            COUIIcons.Light.Paste,
            COUIIcons.Light.Pause,
            COUIIcons.Light.Phone,
            COUIIcons.Light.Photos,
            COUIIcons.Light.Pin,
            COUIIcons.Light.Play,
            COUIIcons.Light.Playlist,
            COUIIcons.Light.Promotions,
            COUIIcons.Light.Recent,
            COUIIcons.Light.Recording,
            COUIIcons.Light.RecordingTape,
            COUIIcons.Light.Redo,
            COUIIcons.Light.Refresh,
            COUIIcons.Light.Remove,
            COUIIcons.Light.RemoveContact,
            COUIIcons.Light.Rename,
            COUIIcons.Light.Replace,
            COUIIcons.Light.Reply,
            COUIIcons.Light.ReplyAll,
            COUIIcons.Light.Report,
            COUIIcons.Light.Reset,
            COUIIcons.Light.RotateLeft,
            COUIIcons.Light.Scan,
            COUIIcons.Light.ScreenCapture,
            COUIIcons.Light.ScreenMirroring,
            COUIIcons.Light.Search,
            COUIIcons.Light.SearchDevice,
            COUIIcons.Light.SelectAll,
            COUIIcons.Light.Send,
            COUIIcons.Light.Settings,
            COUIIcons.Light.Share,
            COUIIcons.Light.Show,
            COUIIcons.Light.Sidebar,
            COUIIcons.Light.Sort,
            COUIIcons.Light.Stopwatch,
            COUIIcons.Light.Store,
            COUIIcons.Light.Tasks,
            COUIIcons.Light.Th1,
            COUIIcons.Light.Th10,
            COUIIcons.Light.Th11,
            COUIIcons.Light.Th12,
            COUIIcons.Light.Th13,
            COUIIcons.Light.Th14,
            COUIIcons.Light.Th15,
            COUIIcons.Light.Th16,
            COUIIcons.Light.Th17,
            COUIIcons.Light.Th18,
            COUIIcons.Light.Th19,
            COUIIcons.Light.Th2,
            COUIIcons.Light.Th20,
            COUIIcons.Light.Th21,
            COUIIcons.Light.Th22,
            COUIIcons.Light.Th23,
            COUIIcons.Light.Th24,
            COUIIcons.Light.Th25,
            COUIIcons.Light.Th26,
            COUIIcons.Light.Th27,
            COUIIcons.Light.Th28,
            COUIIcons.Light.Th29,
            COUIIcons.Light.Th3,
            COUIIcons.Light.Th30,
            COUIIcons.Light.Th31,
            COUIIcons.Light.Th4,
            COUIIcons.Light.Th5,
            COUIIcons.Light.Th6,
            COUIIcons.Light.Th7,
            COUIIcons.Light.Th8,
            COUIIcons.Light.Th9,
            COUIIcons.Light.Theme,
            COUIIcons.Light.Timer,
            COUIIcons.Light.TopDownloads,
            COUIIcons.Light.Translate,
            COUIIcons.Light.Trim,
            COUIIcons.Light.Tune,
            COUIIcons.Light.Undo,
            COUIIcons.Light.Unlock,
            COUIIcons.Light.Unpin,
            COUIIcons.Light.Update,
            COUIIcons.Light.UploadCloud,
            COUIIcons.Light.VerticalSplit,
            COUIIcons.Light.VolumeOff,
            COUIIcons.Light.VolumeUp,
            COUIIcons.Light.Weeks,
            COUIIcons.Light.WorldClock,
            COUIIcons.Light.Years,
            COUIIcons.Light.ZoomOut,
        ),
        "Normal" to listOf(
            COUIIcons.Normal.Add,
            COUIIcons.Normal.AddCircle,
            COUIIcons.Normal.AddFolder,
            COUIIcons.Normal.Alarm,
            COUIIcons.Normal.Album,
            COUIIcons.Normal.All,
            COUIIcons.Normal.Answer,
            COUIIcons.Normal.AppRecording,
            COUIIcons.Normal.Back,
            COUIIcons.Normal.Background,
            COUIIcons.Normal.Backup,
            COUIIcons.Normal.BankCards,
            COUIIcons.Normal.Blocklist,
            COUIIcons.Normal.CallRecording,
            COUIIcons.Normal.Carrier,
            COUIIcons.Normal.ChevronBackward,
            COUIIcons.Normal.ChevronForward,
            COUIIcons.Normal.Clear,
            COUIIcons.Normal.Close,
            COUIIcons.Normal.Close2,
            COUIIcons.Normal.CloudFill,
            COUIIcons.Normal.Community,
            COUIIcons.Normal.Contacts,
            COUIIcons.Normal.ContactsBook,
            COUIIcons.Normal.ContactsCircle,
            COUIIcons.Normal.ConvertFile,
            COUIIcons.Normal.Copy,
            COUIIcons.Normal.Create,
            COUIIcons.Normal.Cut,
            COUIIcons.Normal.Delete,
            COUIIcons.Normal.Download,
            COUIIcons.Normal.Edit,
            COUIIcons.Normal.Email,
            COUIIcons.Normal.ExpandLess,
            COUIIcons.Normal.ExpandMore,
            COUIIcons.Normal.Favorites,
            COUIIcons.Normal.FavoritesFill,
            COUIIcons.Normal.File,
            COUIIcons.Normal.FileDownloads,
            COUIIcons.Normal.Filter,
            COUIIcons.Normal.Folder,
            COUIIcons.Normal.FolderFill,
            COUIIcons.Normal.Forward,
            COUIIcons.Normal.GridView,
            COUIIcons.Normal.Help,
            COUIIcons.Normal.Hide,
            COUIIcons.Normal.HorizontalSplit,
            COUIIcons.Normal.Image,
            COUIIcons.Normal.Import,
            COUIIcons.Normal.Info,
            COUIIcons.Normal.Layers,
            COUIIcons.Normal.Link,
            COUIIcons.Normal.ListView,
            COUIIcons.Normal.Location,
            COUIIcons.Normal.Lock,
            COUIIcons.Normal.MapAlbum,
            COUIIcons.Normal.Merge,
            COUIIcons.Normal.Messages,
            COUIIcons.Normal.Mic,
            COUIIcons.Normal.MicSlash,
            COUIIcons.Normal.MindMap,
            COUIIcons.Normal.Months,
            COUIIcons.Normal.More,
            COUIIcons.Normal.MoreCircle,
            COUIIcons.Normal.MoveFile,
            COUIIcons.Normal.Music,
            COUIIcons.Normal.Notes,
            COUIIcons.Normal.NotesFill,
            COUIIcons.Normal.Ok,
            COUIIcons.Normal.Paste,
            COUIIcons.Normal.Pause,
            COUIIcons.Normal.Phone,
            COUIIcons.Normal.Photos,
            COUIIcons.Normal.Pin,
            COUIIcons.Normal.Play,
            COUIIcons.Normal.Playlist,
            COUIIcons.Normal.Promotions,
            COUIIcons.Normal.Recent,
            COUIIcons.Normal.Recording,
            COUIIcons.Normal.RecordingTape,
            COUIIcons.Normal.Redo,
            COUIIcons.Normal.Refresh,
            COUIIcons.Normal.Remove,
            COUIIcons.Normal.RemoveContact,
            COUIIcons.Normal.Rename,
            COUIIcons.Normal.Replace,
            COUIIcons.Normal.Reply,
            COUIIcons.Normal.ReplyAll,
            COUIIcons.Normal.Report,
            COUIIcons.Normal.Reset,
            COUIIcons.Normal.RotateLeft,
            COUIIcons.Normal.Scan,
            COUIIcons.Normal.ScreenCapture,
            COUIIcons.Normal.ScreenMirroring,
            COUIIcons.Normal.Search,
            COUIIcons.Normal.SearchDevice,
            COUIIcons.Normal.SelectAll,
            COUIIcons.Normal.Send,
            COUIIcons.Normal.Settings,
            COUIIcons.Normal.Share,
            COUIIcons.Normal.Show,
            COUIIcons.Normal.Sidebar,
            COUIIcons.Normal.Sort,
            COUIIcons.Normal.Stopwatch,
            COUIIcons.Normal.Store,
            COUIIcons.Normal.Tasks,
            COUIIcons.Normal.Th1,
            COUIIcons.Normal.Th10,
            COUIIcons.Normal.Th11,
            COUIIcons.Normal.Th12,
            COUIIcons.Normal.Th13,
            COUIIcons.Normal.Th14,
            COUIIcons.Normal.Th15,
            COUIIcons.Normal.Th16,
            COUIIcons.Normal.Th17,
            COUIIcons.Normal.Th18,
            COUIIcons.Normal.Th19,
            COUIIcons.Normal.Th2,
            COUIIcons.Normal.Th20,
            COUIIcons.Normal.Th21,
            COUIIcons.Normal.Th22,
            COUIIcons.Normal.Th23,
            COUIIcons.Normal.Th24,
            COUIIcons.Normal.Th25,
            COUIIcons.Normal.Th26,
            COUIIcons.Normal.Th27,
            COUIIcons.Normal.Th28,
            COUIIcons.Normal.Th29,
            COUIIcons.Normal.Th3,
            COUIIcons.Normal.Th30,
            COUIIcons.Normal.Th31,
            COUIIcons.Normal.Th4,
            COUIIcons.Normal.Th5,
            COUIIcons.Normal.Th6,
            COUIIcons.Normal.Th7,
            COUIIcons.Normal.Th8,
            COUIIcons.Normal.Th9,
            COUIIcons.Normal.Theme,
            COUIIcons.Normal.Timer,
            COUIIcons.Normal.TopDownloads,
            COUIIcons.Normal.Translate,
            COUIIcons.Normal.Trim,
            COUIIcons.Normal.Tune,
            COUIIcons.Normal.Undo,
            COUIIcons.Normal.Unlock,
            COUIIcons.Normal.Unpin,
            COUIIcons.Normal.Update,
            COUIIcons.Normal.UploadCloud,
            COUIIcons.Normal.VerticalSplit,
            COUIIcons.Normal.VolumeOff,
            COUIIcons.Normal.VolumeUp,
            COUIIcons.Normal.Weeks,
            COUIIcons.Normal.WorldClock,
            COUIIcons.Normal.Years,
            COUIIcons.Normal.ZoomOut,
        ),
        "Regular" to listOf(
            COUIIcons.Regular.Add,
            COUIIcons.Regular.AddCircle,
            COUIIcons.Regular.AddFolder,
            COUIIcons.Regular.Alarm,
            COUIIcons.Regular.Album,
            COUIIcons.Regular.All,
            COUIIcons.Regular.Answer,
            COUIIcons.Regular.AppRecording,
            COUIIcons.Regular.Back,
            COUIIcons.Regular.Background,
            COUIIcons.Regular.Backup,
            COUIIcons.Regular.BankCards,
            COUIIcons.Regular.Blocklist,
            COUIIcons.Regular.CallRecording,
            COUIIcons.Regular.Carrier,
            COUIIcons.Regular.ChevronBackward,
            COUIIcons.Regular.ChevronForward,
            COUIIcons.Regular.Clear,
            COUIIcons.Regular.Close,
            COUIIcons.Regular.Close2,
            COUIIcons.Regular.CloudFill,
            COUIIcons.Regular.Community,
            COUIIcons.Regular.Contacts,
            COUIIcons.Regular.ContactsBook,
            COUIIcons.Regular.ContactsCircle,
            COUIIcons.Regular.ConvertFile,
            COUIIcons.Regular.Copy,
            COUIIcons.Regular.Create,
            COUIIcons.Regular.Cut,
            COUIIcons.Regular.Delete,
            COUIIcons.Regular.Download,
            COUIIcons.Regular.Edit,
            COUIIcons.Regular.Email,
            COUIIcons.Regular.ExpandLess,
            COUIIcons.Regular.ExpandMore,
            COUIIcons.Regular.Favorites,
            COUIIcons.Regular.FavoritesFill,
            COUIIcons.Regular.File,
            COUIIcons.Regular.FileDownloads,
            COUIIcons.Regular.Filter,
            COUIIcons.Regular.Folder,
            COUIIcons.Regular.FolderFill,
            COUIIcons.Regular.Forward,
            COUIIcons.Regular.GridView,
            COUIIcons.Regular.Help,
            COUIIcons.Regular.Hide,
            COUIIcons.Regular.HorizontalSplit,
            COUIIcons.Regular.Image,
            COUIIcons.Regular.Import,
            COUIIcons.Regular.Info,
            COUIIcons.Regular.Layers,
            COUIIcons.Regular.Link,
            COUIIcons.Regular.ListView,
            COUIIcons.Regular.Location,
            COUIIcons.Regular.Lock,
            COUIIcons.Regular.MapAlbum,
            COUIIcons.Regular.Merge,
            COUIIcons.Regular.Messages,
            COUIIcons.Regular.Mic,
            COUIIcons.Regular.MicSlash,
            COUIIcons.Regular.MindMap,
            COUIIcons.Regular.Months,
            COUIIcons.Regular.More,
            COUIIcons.Regular.MoreCircle,
            COUIIcons.Regular.MoveFile,
            COUIIcons.Regular.Music,
            COUIIcons.Regular.Notes,
            COUIIcons.Regular.NotesFill,
            COUIIcons.Regular.Ok,
            COUIIcons.Regular.Paste,
            COUIIcons.Regular.Pause,
            COUIIcons.Regular.Phone,
            COUIIcons.Regular.Photos,
            COUIIcons.Regular.Pin,
            COUIIcons.Regular.Play,
            COUIIcons.Regular.Playlist,
            COUIIcons.Regular.Promotions,
            COUIIcons.Regular.Recent,
            COUIIcons.Regular.Recording,
            COUIIcons.Regular.RecordingTape,
            COUIIcons.Regular.Redo,
            COUIIcons.Regular.Refresh,
            COUIIcons.Regular.Remove,
            COUIIcons.Regular.RemoveContact,
            COUIIcons.Regular.Rename,
            COUIIcons.Regular.Replace,
            COUIIcons.Regular.Reply,
            COUIIcons.Regular.ReplyAll,
            COUIIcons.Regular.Report,
            COUIIcons.Regular.Reset,
            COUIIcons.Regular.RotateLeft,
            COUIIcons.Regular.Scan,
            COUIIcons.Regular.ScreenCapture,
            COUIIcons.Regular.ScreenMirroring,
            COUIIcons.Regular.Search,
            COUIIcons.Regular.SearchDevice,
            COUIIcons.Regular.SelectAll,
            COUIIcons.Regular.Send,
            COUIIcons.Regular.Settings,
            COUIIcons.Regular.Share,
            COUIIcons.Regular.Show,
            COUIIcons.Regular.Sidebar,
            COUIIcons.Regular.Sort,
            COUIIcons.Regular.Stopwatch,
            COUIIcons.Regular.Store,
            COUIIcons.Regular.Tasks,
            COUIIcons.Regular.Th1,
            COUIIcons.Regular.Th10,
            COUIIcons.Regular.Th11,
            COUIIcons.Regular.Th12,
            COUIIcons.Regular.Th13,
            COUIIcons.Regular.Th14,
            COUIIcons.Regular.Th15,
            COUIIcons.Regular.Th16,
            COUIIcons.Regular.Th17,
            COUIIcons.Regular.Th18,
            COUIIcons.Regular.Th19,
            COUIIcons.Regular.Th2,
            COUIIcons.Regular.Th20,
            COUIIcons.Regular.Th21,
            COUIIcons.Regular.Th22,
            COUIIcons.Regular.Th23,
            COUIIcons.Regular.Th24,
            COUIIcons.Regular.Th25,
            COUIIcons.Regular.Th26,
            COUIIcons.Regular.Th27,
            COUIIcons.Regular.Th28,
            COUIIcons.Regular.Th29,
            COUIIcons.Regular.Th3,
            COUIIcons.Regular.Th30,
            COUIIcons.Regular.Th31,
            COUIIcons.Regular.Th4,
            COUIIcons.Regular.Th5,
            COUIIcons.Regular.Th6,
            COUIIcons.Regular.Th7,
            COUIIcons.Regular.Th8,
            COUIIcons.Regular.Th9,
            COUIIcons.Regular.Theme,
            COUIIcons.Regular.Timer,
            COUIIcons.Regular.TopDownloads,
            COUIIcons.Regular.Translate,
            COUIIcons.Regular.Trim,
            COUIIcons.Regular.Tune,
            COUIIcons.Regular.Undo,
            COUIIcons.Regular.Unlock,
            COUIIcons.Regular.Unpin,
            COUIIcons.Regular.Update,
            COUIIcons.Regular.UploadCloud,
            COUIIcons.Regular.VerticalSplit,
            COUIIcons.Regular.VolumeOff,
            COUIIcons.Regular.VolumeUp,
            COUIIcons.Regular.Weeks,
            COUIIcons.Regular.WorldClock,
            COUIIcons.Regular.Years,
            COUIIcons.Regular.ZoomOut,
        ),
        "Medium" to listOf(
            COUIIcons.Medium.Add,
            COUIIcons.Medium.AddCircle,
            COUIIcons.Medium.AddFolder,
            COUIIcons.Medium.Alarm,
            COUIIcons.Medium.Album,
            COUIIcons.Medium.All,
            COUIIcons.Medium.Answer,
            COUIIcons.Medium.AppRecording,
            COUIIcons.Medium.Back,
            COUIIcons.Medium.Background,
            COUIIcons.Medium.Backup,
            COUIIcons.Medium.BankCards,
            COUIIcons.Medium.Blocklist,
            COUIIcons.Medium.CallRecording,
            COUIIcons.Medium.Carrier,
            COUIIcons.Medium.ChevronBackward,
            COUIIcons.Medium.ChevronForward,
            COUIIcons.Medium.Clear,
            COUIIcons.Medium.Close,
            COUIIcons.Medium.Close2,
            COUIIcons.Medium.CloudFill,
            COUIIcons.Medium.Community,
            COUIIcons.Medium.Contacts,
            COUIIcons.Medium.ContactsBook,
            COUIIcons.Medium.ContactsCircle,
            COUIIcons.Medium.ConvertFile,
            COUIIcons.Medium.Copy,
            COUIIcons.Medium.Create,
            COUIIcons.Medium.Cut,
            COUIIcons.Medium.Delete,
            COUIIcons.Medium.Download,
            COUIIcons.Medium.Edit,
            COUIIcons.Medium.Email,
            COUIIcons.Medium.ExpandLess,
            COUIIcons.Medium.ExpandMore,
            COUIIcons.Medium.Favorites,
            COUIIcons.Medium.FavoritesFill,
            COUIIcons.Medium.File,
            COUIIcons.Medium.FileDownloads,
            COUIIcons.Medium.Filter,
            COUIIcons.Medium.Folder,
            COUIIcons.Medium.FolderFill,
            COUIIcons.Medium.Forward,
            COUIIcons.Medium.GridView,
            COUIIcons.Medium.Help,
            COUIIcons.Medium.Hide,
            COUIIcons.Medium.HorizontalSplit,
            COUIIcons.Medium.Image,
            COUIIcons.Medium.Import,
            COUIIcons.Medium.Info,
            COUIIcons.Medium.Layers,
            COUIIcons.Medium.Link,
            COUIIcons.Medium.ListView,
            COUIIcons.Medium.Location,
            COUIIcons.Medium.Lock,
            COUIIcons.Medium.MapAlbum,
            COUIIcons.Medium.Merge,
            COUIIcons.Medium.Messages,
            COUIIcons.Medium.Mic,
            COUIIcons.Medium.MicSlash,
            COUIIcons.Medium.MindMap,
            COUIIcons.Medium.Months,
            COUIIcons.Medium.More,
            COUIIcons.Medium.MoreCircle,
            COUIIcons.Medium.MoveFile,
            COUIIcons.Medium.Music,
            COUIIcons.Medium.Notes,
            COUIIcons.Medium.NotesFill,
            COUIIcons.Medium.Ok,
            COUIIcons.Medium.Paste,
            COUIIcons.Medium.Pause,
            COUIIcons.Medium.Phone,
            COUIIcons.Medium.Photos,
            COUIIcons.Medium.Pin,
            COUIIcons.Medium.Play,
            COUIIcons.Medium.Playlist,
            COUIIcons.Medium.Promotions,
            COUIIcons.Medium.Recent,
            COUIIcons.Medium.Recording,
            COUIIcons.Medium.RecordingTape,
            COUIIcons.Medium.Redo,
            COUIIcons.Medium.Refresh,
            COUIIcons.Medium.Remove,
            COUIIcons.Medium.RemoveContact,
            COUIIcons.Medium.Rename,
            COUIIcons.Medium.Replace,
            COUIIcons.Medium.Reply,
            COUIIcons.Medium.ReplyAll,
            COUIIcons.Medium.Report,
            COUIIcons.Medium.Reset,
            COUIIcons.Medium.RotateLeft,
            COUIIcons.Medium.Scan,
            COUIIcons.Medium.ScreenCapture,
            COUIIcons.Medium.ScreenMirroring,
            COUIIcons.Medium.Search,
            COUIIcons.Medium.SearchDevice,
            COUIIcons.Medium.SelectAll,
            COUIIcons.Medium.Send,
            COUIIcons.Medium.Settings,
            COUIIcons.Medium.Share,
            COUIIcons.Medium.Show,
            COUIIcons.Medium.Sidebar,
            COUIIcons.Medium.Sort,
            COUIIcons.Medium.Stopwatch,
            COUIIcons.Medium.Store,
            COUIIcons.Medium.Tasks,
            COUIIcons.Medium.Th1,
            COUIIcons.Medium.Th10,
            COUIIcons.Medium.Th11,
            COUIIcons.Medium.Th12,
            COUIIcons.Medium.Th13,
            COUIIcons.Medium.Th14,
            COUIIcons.Medium.Th15,
            COUIIcons.Medium.Th16,
            COUIIcons.Medium.Th17,
            COUIIcons.Medium.Th18,
            COUIIcons.Medium.Th19,
            COUIIcons.Medium.Th2,
            COUIIcons.Medium.Th20,
            COUIIcons.Medium.Th21,
            COUIIcons.Medium.Th22,
            COUIIcons.Medium.Th23,
            COUIIcons.Medium.Th24,
            COUIIcons.Medium.Th25,
            COUIIcons.Medium.Th26,
            COUIIcons.Medium.Th27,
            COUIIcons.Medium.Th28,
            COUIIcons.Medium.Th29,
            COUIIcons.Medium.Th3,
            COUIIcons.Medium.Th30,
            COUIIcons.Medium.Th31,
            COUIIcons.Medium.Th4,
            COUIIcons.Medium.Th5,
            COUIIcons.Medium.Th6,
            COUIIcons.Medium.Th7,
            COUIIcons.Medium.Th8,
            COUIIcons.Medium.Th9,
            COUIIcons.Medium.Theme,
            COUIIcons.Medium.Timer,
            COUIIcons.Medium.TopDownloads,
            COUIIcons.Medium.Translate,
            COUIIcons.Medium.Trim,
            COUIIcons.Medium.Tune,
            COUIIcons.Medium.Undo,
            COUIIcons.Medium.Unlock,
            COUIIcons.Medium.Unpin,
            COUIIcons.Medium.Update,
            COUIIcons.Medium.UploadCloud,
            COUIIcons.Medium.VerticalSplit,
            COUIIcons.Medium.VolumeOff,
            COUIIcons.Medium.VolumeUp,
            COUIIcons.Medium.Weeks,
            COUIIcons.Medium.WorldClock,
            COUIIcons.Medium.Years,
            COUIIcons.Medium.ZoomOut,
        ),
        "Demibold" to listOf(
            COUIIcons.Demibold.Add,
            COUIIcons.Demibold.AddCircle,
            COUIIcons.Demibold.AddFolder,
            COUIIcons.Demibold.Alarm,
            COUIIcons.Demibold.Album,
            COUIIcons.Demibold.All,
            COUIIcons.Demibold.Answer,
            COUIIcons.Demibold.AppRecording,
            COUIIcons.Demibold.Back,
            COUIIcons.Demibold.Background,
            COUIIcons.Demibold.Backup,
            COUIIcons.Demibold.BankCards,
            COUIIcons.Demibold.Blocklist,
            COUIIcons.Demibold.CallRecording,
            COUIIcons.Demibold.Carrier,
            COUIIcons.Demibold.ChevronBackward,
            COUIIcons.Demibold.ChevronForward,
            COUIIcons.Demibold.Clear,
            COUIIcons.Demibold.Close,
            COUIIcons.Demibold.Close2,
            COUIIcons.Demibold.CloudFill,
            COUIIcons.Demibold.Community,
            COUIIcons.Demibold.Contacts,
            COUIIcons.Demibold.ContactsBook,
            COUIIcons.Demibold.ContactsCircle,
            COUIIcons.Demibold.ConvertFile,
            COUIIcons.Demibold.Copy,
            COUIIcons.Demibold.Create,
            COUIIcons.Demibold.Cut,
            COUIIcons.Demibold.Delete,
            COUIIcons.Demibold.Download,
            COUIIcons.Demibold.Edit,
            COUIIcons.Demibold.Email,
            COUIIcons.Demibold.ExpandLess,
            COUIIcons.Demibold.ExpandMore,
            COUIIcons.Demibold.Favorites,
            COUIIcons.Demibold.FavoritesFill,
            COUIIcons.Demibold.File,
            COUIIcons.Demibold.FileDownloads,
            COUIIcons.Demibold.Filter,
            COUIIcons.Demibold.Folder,
            COUIIcons.Demibold.FolderFill,
            COUIIcons.Demibold.Forward,
            COUIIcons.Demibold.GridView,
            COUIIcons.Demibold.Help,
            COUIIcons.Demibold.Hide,
            COUIIcons.Demibold.HorizontalSplit,
            COUIIcons.Demibold.Image,
            COUIIcons.Demibold.Import,
            COUIIcons.Demibold.Info,
            COUIIcons.Demibold.Layers,
            COUIIcons.Demibold.Link,
            COUIIcons.Demibold.ListView,
            COUIIcons.Demibold.Location,
            COUIIcons.Demibold.Lock,
            COUIIcons.Demibold.MapAlbum,
            COUIIcons.Demibold.Merge,
            COUIIcons.Demibold.Messages,
            COUIIcons.Demibold.Mic,
            COUIIcons.Demibold.MicSlash,
            COUIIcons.Demibold.MindMap,
            COUIIcons.Demibold.Months,
            COUIIcons.Demibold.More,
            COUIIcons.Demibold.MoreCircle,
            COUIIcons.Demibold.MoveFile,
            COUIIcons.Demibold.Music,
            COUIIcons.Demibold.Notes,
            COUIIcons.Demibold.NotesFill,
            COUIIcons.Demibold.Ok,
            COUIIcons.Demibold.Paste,
            COUIIcons.Demibold.Pause,
            COUIIcons.Demibold.Phone,
            COUIIcons.Demibold.Photos,
            COUIIcons.Demibold.Pin,
            COUIIcons.Demibold.Play,
            COUIIcons.Demibold.Playlist,
            COUIIcons.Demibold.Promotions,
            COUIIcons.Demibold.Recent,
            COUIIcons.Demibold.Recording,
            COUIIcons.Demibold.RecordingTape,
            COUIIcons.Demibold.Redo,
            COUIIcons.Demibold.Refresh,
            COUIIcons.Demibold.Remove,
            COUIIcons.Demibold.RemoveContact,
            COUIIcons.Demibold.Rename,
            COUIIcons.Demibold.Replace,
            COUIIcons.Demibold.Reply,
            COUIIcons.Demibold.ReplyAll,
            COUIIcons.Demibold.Report,
            COUIIcons.Demibold.Reset,
            COUIIcons.Demibold.RotateLeft,
            COUIIcons.Demibold.Scan,
            COUIIcons.Demibold.ScreenCapture,
            COUIIcons.Demibold.ScreenMirroring,
            COUIIcons.Demibold.Search,
            COUIIcons.Demibold.SearchDevice,
            COUIIcons.Demibold.SelectAll,
            COUIIcons.Demibold.Send,
            COUIIcons.Demibold.Settings,
            COUIIcons.Demibold.Share,
            COUIIcons.Demibold.Show,
            COUIIcons.Demibold.Sidebar,
            COUIIcons.Demibold.Sort,
            COUIIcons.Demibold.Stopwatch,
            COUIIcons.Demibold.Store,
            COUIIcons.Demibold.Tasks,
            COUIIcons.Demibold.Th1,
            COUIIcons.Demibold.Th10,
            COUIIcons.Demibold.Th11,
            COUIIcons.Demibold.Th12,
            COUIIcons.Demibold.Th13,
            COUIIcons.Demibold.Th14,
            COUIIcons.Demibold.Th15,
            COUIIcons.Demibold.Th16,
            COUIIcons.Demibold.Th17,
            COUIIcons.Demibold.Th18,
            COUIIcons.Demibold.Th19,
            COUIIcons.Demibold.Th2,
            COUIIcons.Demibold.Th20,
            COUIIcons.Demibold.Th21,
            COUIIcons.Demibold.Th22,
            COUIIcons.Demibold.Th23,
            COUIIcons.Demibold.Th24,
            COUIIcons.Demibold.Th25,
            COUIIcons.Demibold.Th26,
            COUIIcons.Demibold.Th27,
            COUIIcons.Demibold.Th28,
            COUIIcons.Demibold.Th29,
            COUIIcons.Demibold.Th3,
            COUIIcons.Demibold.Th30,
            COUIIcons.Demibold.Th31,
            COUIIcons.Demibold.Th4,
            COUIIcons.Demibold.Th5,
            COUIIcons.Demibold.Th6,
            COUIIcons.Demibold.Th7,
            COUIIcons.Demibold.Th8,
            COUIIcons.Demibold.Th9,
            COUIIcons.Demibold.Theme,
            COUIIcons.Demibold.Timer,
            COUIIcons.Demibold.TopDownloads,
            COUIIcons.Demibold.Translate,
            COUIIcons.Demibold.Trim,
            COUIIcons.Demibold.Tune,
            COUIIcons.Demibold.Undo,
            COUIIcons.Demibold.Unlock,
            COUIIcons.Demibold.Unpin,
            COUIIcons.Demibold.Update,
            COUIIcons.Demibold.UploadCloud,
            COUIIcons.Demibold.VerticalSplit,
            COUIIcons.Demibold.VolumeOff,
            COUIIcons.Demibold.VolumeUp,
            COUIIcons.Demibold.Weeks,
            COUIIcons.Demibold.WorldClock,
            COUIIcons.Demibold.Years,
            COUIIcons.Demibold.ZoomOut,
        ),
    )
