// Copyright 2025, compose-miuix-ui contributors
// SPDX-License-Identifier: Apache-2.0
package top.yukonga.miuix.kmp.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.ui.graphics.Color

internal fun mapMd3ToMiuixColorsCommon(cs: ColorScheme, dark: Boolean): Colors {
    return Colors(
        primary = cs.primary,
        onPrimary = cs.onPrimary,
        primaryVariant = cs.primaryFixed,
        onPrimaryVariant = cs.onPrimaryFixed,
        error = cs.error,
        onError = cs.onError,
        errorContainer = cs.errorContainer,
        onErrorContainer = cs.onErrorContainer,
        disabledPrimary = cs.primary.copy(alpha = 0.38f),
        disabledOnPrimary = cs.onPrimary.copy(alpha = 0.38f),
        disabledPrimaryButton = cs.primary.copy(alpha = 0.38f),
        disabledOnPrimaryButton = cs.onPrimary.copy(alpha = 0.6f),
        disabledPrimarySlider = cs.secondary.copy(alpha = 0.38f),
        primaryContainer = cs.primaryContainer,
        onPrimaryContainer = cs.onPrimaryContainer,
        secondary = cs.secondary.copy(alpha = 0.38f),
        onSecondary = cs.onSecondary,
        secondaryVariant = cs.primary.copy(alpha = 0.24f),
        onSecondaryVariant = cs.secondary,
        disabledSecondary = cs.secondary.copy(alpha = 0.38f),
        disabledOnSecondary = cs.onSecondary.copy(alpha = 0.38f),
        disabledSecondaryVariant = cs.secondary.copy(alpha = 0.12f),
        disabledOnSecondaryVariant = cs.secondary.copy(alpha = 0.6f),
        secondaryContainer = cs.secondaryContainer,
        onSecondaryContainer = cs.onSecondaryContainer,
        secondaryContainerVariant = cs.secondaryContainer,
        onSecondaryContainerVariant = cs.onSecondaryContainer,
        tertiaryContainer = cs.tertiaryContainer,
        onTertiaryContainer = cs.onTertiaryContainer,
        tertiaryContainerVariant = cs.onTertiaryContainer, // cs.onSurfaceVariant.copy(alpha = 0.3f),
        background = cs.background,
        onBackground = cs.onBackground,
        onBackgroundVariant = cs.primary,
        surface = cs.surface,
        onSurface = cs.onSurface,
        surfaceVariant = cs.surfaceVariant,
        onSurfaceSecondary = cs.onSurface.copy(alpha = 0.8f),
        onSurfaceVariantSummary = cs.onSurface.copy(alpha = 0.6f),
        onSurfaceVariantActions = cs.onSurface.copy(alpha = 0.6f),
        disabledOnSurface = cs.onSurface,
        surfaceContainer = cs.surfaceContainer,
        onSurfaceContainer = cs.onSurface,
        onSurfaceContainerVariant = cs.onSurfaceVariant.copy(alpha = 0.6f),
        surfaceContainerHigh = cs.surfaceVariant,
        onSurfaceContainerHigh = cs.onSurface.copy(alpha = 0.8f),
        surfaceContainerHighest = if (dark) Color(0xFF2D2D2D) else Color(0xFFE8E8E8),
        onSurfaceContainerHighest = cs.onSurface,
        outline = cs.outline,
        dividerLine = cs.outlineVariant,
        windowDimming = if (dark) Color.Black.copy(alpha = 0.6f) else Color.Black.copy(alpha = 0.3f),
        sliderKeyPoint = cs.onSecondaryContainer,
        sliderKeyPointForeground = cs.onPrimary,
    )
}
